version: '3.8'

services:
  fiber-app:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "6060:6060"
    networks:
      - app-network

  nextjs-app:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge